In [ ]:
# Создайте массив из 10 нулей
import numpy as np
b = np.zeros((10))
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# Создать массив из 10 единиц
import numpy as np
c = np.ones((10))
print(c)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# Создать массив из 10 пятерок
import numpy as np
d = np.ones(10)*5
print(d)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
# Создать массив из целых чисел от 10 до 50
import numpy as np
e = np.arange(10, 50)
print(e)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Создать массив из четных чисел от 10 до 50
import numpy as np
f = np.arange(10, 50, 2)
print(f)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [ ]:
# Создать матрицу 3х3 с числами от 0 до 8
import numpy as np
g = np.arange(0, 9).reshape(3, 3)
print(g)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Создать единичную матрицу 3x3
import numpy as np
h = np.eye(3)
print(h)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Используйте NumPy для генерации случайного числа от 0 до 1
import numpy as np
i = np.random.normal(0,1)
print(i)

0.12879513663832606


In [ ]:
# Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения
import numpy as np
j = np.random.normal(0,1,25)
print(j)

[-0.99241476 -0.24834339 -0.25117902  0.07519485  1.14923038  0.62267128
  0.99696305  0.08068752  2.08970302 -1.1629747   1.07208191  0.35845386
 -0.05294088 -0.29060227 -0.21039429 -1.56930027  1.12479496  0.91493157
  1.13240527  0.94261787  1.44910797 -0.27402983  0.05144615 -0.34597619
 -0.820193  ]


In [ ]:
# Создайте матрицу используя функции библиотеки NumPy
import numpy as np
k = np.linspace(0, 1, 101)
print(k)

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]


In [ ]:
# Необходимо написать код который вернет матрицу из стартовой
import numpy as np
mat = np.arange(1,26).reshape(5,5) # Стартовая матрица
print(mat[2:5, 1:5])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
# Написать код обращения к элементу который вернет значение  20 из стартовой матрицы
import numpy as np
mat = np.arange(1,26).reshape(5,5) # Стартовая матрица
print(mat[3][4])

20


In [ ]:
# Написать код к стартовой матрице, который воспроизводит вывод
import numpy as np
mat = np.arange(1,26).reshape(5,5) # Стартовая матрица
v = mat[0:3, 1].reshape(3,1)
print(v)

[[ 2]
 [ 7]
 [12]]


In [ ]:
# Написать код к стартовой матрице, который воспроизводит вывод
import numpy as np
mat = np.arange(1,26).reshape(5,5) # Стартовая матрица
print(mat[4, :])

[21 22 23 24 25]


In [ ]:
# Написать код к стартовой матрице, который воспроизводит вывод
import numpy as np
mat = np.arange(1,26).reshape(5,5) # Стартовая матрица
print(mat[3:5, :])

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
# Получить сумму всех значений в стартовой матрице mat
import numpy as np
mat = np.arange(1,26).reshape(5,5) # Стартовая матрица
print(np.sum(mat))

325


In [ ]:
# Получить стандартное отклонение в стартовой матрице mat
import numpy as np
mat = np.arange(1,26).reshape(5,5) # Стартовая матрица
print(np.std(mat))

7.211102550927978


In [ ]:
# Получить сумму значений в колонках в стартовой матрице mat
import numpy as np
mat = np.arange(1,26).reshape(5,5) # Стартовая матрица
print(mat.sum(axis=0))

[55 60 65 70 75]
